version: "3"
services:
  user:
    image: pika:spike
    build:
      context: .
    volumes:
      - .:/opt/app
    ports:
      - "5001:5000"
    environment:
      - PROJECT_NAME=user
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
  score:
    image: pika:spike
    volumes:
      - .:/opt/app
    environment:
      - PROJECT_NAME=score
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
    ports:
      - "5002:5000"
  money:
    image: pika:spike
    volumes:
      - .:/opt/app
    environment:
      - PROJECT_NAME=money
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
    ports:
      - "5003:5000"
  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
  mongo_user:
    image: mongo:latest
  mongo_score:
    image: mongo:latest
  mongo_money:
    image: mongo:latest
    